sudo: required
cache: docker

services: 
  - docker

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

env:
  global:
    - skip_ruby_from_ppa=true

env:
  - UBUNTU_VERSION=18.04
  - UBUNTU_VERSION=16.04
  - UBUNTU_VERSION=14.04

env:
  - SWIFT_VERSION=4.2
  - SWIFT_VERSION=4.1
  - SWIFT_VERSION=4.0.3

script:
  - docker image build -t swift-nio:$UBUNTU_VERSION.$SWIFT_VERSION --build-arg=ubuntu_version=$UBUNTU_VERSION --build-arg=swift_version=$SWIFT_VERSION .
  - docker tag swift-nio:$UBUNTU_VERSION.$SWIFT_VERSION mattpaletta/swift-nio:$UBUNTU_VERSION.$SWIFT_VERSION

after_success:
  - docker push mattpaletta/swift-nio:$UBUNTU_VERSION.$SWIFT_VERSION
